baseURL: https://services.theobori.cafe
languageCode: fr-fr
defaultContentLanguage: fr
title: Théo Bori's services
theme: cupper-hugo-theme
# googleAnalytics: UA-123456789-1
# disqusShortname: yourdiscussshortname
# enableGitInfo: true

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  homeMetaContent: Des services libres
  footer: |
    [Mentions légales](/legal)
    [Conditions d'utilisation](/cgu)
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Oct 31, 2023
  codePenUser: theobori
  katex: true
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: false
  defaultDarkTheme: false
  moveFooterToHeader: true
  navTitleText: Théo Bori's services
  # logoAlt: An alternative text description of the logo
  # customCss:
  #   - css/custom_01.css
  #   - css/custom_02.css
  # customJs:
  #   - js/custom_01.js
  #   - js/custom_02.js
  # utterances:
  #   repo: username/username.github.io
  #   issueTerm: title
  #   theme: github-dark

menu:
  nav:
    - name: Accueil
      url: /
      weight: 1
    - name: Services
      url: /services/
      weight: 2
    - name: Ressources
      url: /ressources/
      weight: 3
    - name: Informations
      url: /informations/
      weight: 4

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
